/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package giocatore_completo_1;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;

/**
 *
 * @author dippolito_mattia
 */
public class FrameGioco extends javax.swing.JFrame {

    JGiocatore giocatore;
    JGiocatore giocatore_avversario;
    static JCondivisa condivisa;
    
    public FrameGioco(JCondivisa condivisa) {
        initComponents();
        this.setExtendedState(FrameGioco.MAXIMIZED_BOTH);
        this.setVisible(true);
        this.condivisa = condivisa;
        Gestore_messaggio gm = new Gestore_messaggio(condivisa);
        
        giocatore = new JGiocatore("Personaggio", this, 10);
        giocatore_avversario = new JGiocatore("Personaggio", this, 10);
        
        this.addKeyListener(new keyEvent_movimento(giocatore));
        this.addKeyListener(new keyEvent_salta(giocatore, condivisa));
        
        Disegna d = new Disegna(this, 30);
        Thread_invio_pos tip = new Thread_invio_pos(giocatore, 30, this.getWidth(), gm);
        Thread_invio_salto tis = new Thread_invio_salto(giocatore, gm);
        Thread_ricezione_messaggi trm = new Thread_ricezione_messaggi(condivisa, giocatore_avversario, this.getWidth(), gm);
        
        tip.start();
        tis.start();
        trm.start();
        d.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameGioco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameGioco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameGioco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameGioco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameGioco(condivisa).setVisible(true);
            }
        });
    }

    @Override
    public void paint(Graphics g) {
        Image offscreen = createImage(this.getWidth(), this.getHeight());
        Graphics offgc = offscreen.getGraphics();
        
        //DISEGNO LINEA TERRENO
        offgc.setColor(Color.black);
        offgc.drawLine(0, 510, this.getWidth(), 510);
        
        //DISEGNO GIOCATORE SINISTRA
        offgc.setColor(Color.green);
        offgc.fillRect(giocatore.getPos_x(), giocatore.getPos_y(), 10, 10);
        giocatore.Update();
        
        //DISEGNO GIOCATORE DESTRA
        offgc.setColor(Color.red);
        offgc.fillRect(giocatore_avversario.getPos_x(), giocatore_avversario.getPos_y(), 10, 10);

        g.drawImage(offscreen, 0, 0, null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
